version: "3"
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./api/:/go/src/main
    ports:
      - 8080:8080

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./app/:/src
    ports:
      - 3000:3000

  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    env_file: ./db/.env