info:
  contact: {}
  license: {}
paths:
  /articles:
    get:
      consumes:
      - application/json
      parameters:
      - default: "2019-01-19T14:13:01Z"
        description: Only articles published at or after this time are returned.
        in: query
        name: since
        type: string
      - description: Only articles published at or before this time are returned.
        in: query
        name: until
        type: string
      - default: desc
        description: The direction of the sort by pub_date
        enum:
        - desc
        - asc
        in: query
        name: sort
        type: string
      - default: 50
        description: The number of articles that you can get the result
        in: query
        maximum: 50
        minimum: 1
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/Article'
            type: object
      summary: Get articles
      tags:
      - articles
    post:
      consumes:
      - application/json
      parameters:
      - description: article
        in: body
        name: article
        required: true
        schema:
          $ref: '#/definitions/CreateArticleForm'
          type: object
      produces:
      - application/json
      responses:
        "200": {}
      summary: Add a new article
      tags:
      - articles
